import { callBackend } from '../transport'
import type { ColdPassEntry } from '../../types/coldpass'
import type { ColdPassPasswordOptions } from './passwordGenerator'

/** Unlocked vault as rendered by the UI. The passkey stays in the backend. */
export interface ColdPassSessionData {
  entries: ColdPassEntry[]
}

/** CSV parsed by the backend and waiting for the passkey confirmation. */
export interface ColdPassImportPreview {
  sourceFileName: string
  importedCount: number
  skippedRowCount: number
}

async function invokeColdPass<T>(command: string, payload: Record<string, unknown>): Promise<T> {
  try {
    return await callBackend<T>(command, { payload })
  } catch (error) {
    if (error instanceof Error) throw error
    const message = error && typeof error === 'object' && typeof (error as { message?: unknown }).message === 'string'
      ? (error as { message: string }).message
      : 'No se pudo completar la operación de ColdPass.'
    throw new Error(message)
  }
}

export async function unlockColdPassSession(libraryId: string, passkey: string): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_unlock', { libraryId, passkey })
}

export async function lockColdPassSession(libraryId: string): Promise<void> {
  await invokeColdPass('coldpass_lock', { libraryId })
}

/** Adds a credential, or edits `entryId` keeping its password history. */
export async function saveColdPassEntry(
  libraryId: string,
  entry: ColdPassEntry,
  entryId?: string,
): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_save_entry', {
    libraryId,
    entry,
    ...(entryId ? { entryId } : {}),
  })
}

export async function deleteColdPassEntry(
  libraryId: string,
  entryId: string,
  passkey: string,
): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_delete_entry', { libraryId, entryId, passkey })
}

/** Opens the native picker in the backend; `null` when cancelled. */
export async function pickColdPassCsvImport(libraryId: string): Promise<ColdPassImportPreview | null> {
  return invokeColdPass<ColdPassImportPreview | null>('coldpass_pick_csv_import', { libraryId })
}

export async function confirmColdPassImport(libraryId: string, passkey: string): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_confirm_import', { libraryId, passkey })
}

/** Whether the library already has a vault; a first unlock creates it. */
export async function getColdPassStatus(libraryId: string): Promise<{ exists: boolean }> {
  return invokeColdPass<{ exists: boolean }>('coldpass_status', { libraryId })
}

/** A random password generated by the backend and its brute-force estimate. */
export async function generateColdPassPassword(
  options: ColdPassPasswordOptions,
): Promise<{ password: string; bruteForceSeconds: number }> {
  return invokeColdPass<{ password: string; bruteForceSeconds: number }>('coldpass_generate_password', { options })
}
