import { callBackend } from '../transport'
import type { ColdPassEntry, ColdPassEntryView } from '../../types/coldpass'
import type { ColdPassPasswordOptions } from './passwordGenerator'

/** Unlocked vault as rendered by the UI. The vault key stays in the backend. */
export interface ColdPassSessionData {
  entries: ColdPassEntryView[]
}

/** CSV parsed by the backend and waiting for the Owner's password. */
export interface ColdPassImportPreview {
  sourceFileName: string
  importedCount: number
  skippedRowCount: number
}

/** Whether the library has a vault and whether it still uses its old passkey. */
export interface ColdPassStatus {
  exists: boolean
  needsLegacyPasskey: boolean
}

async function invokeColdPass<T>(command: string, payload: Record<string, unknown>): Promise<T> {
  try {
    return await callBackend<T>(command, { payload })
  } catch (error) {
    if (error instanceof Error) throw error
    const message = error && typeof error === 'object' && typeof (error as { message?: unknown }).message === 'string'
      ? (error as { message: string }).message
      : 'No se pudo completar la operación de ColdPass.'
    throw new Error(message)
  }
}

/**
 * Opens the vault with the Owner's password. `legacyPasskey` is the passkey
 * of a vault from before, asked once to move it to the Owner's key.
 */
export async function unlockColdPassSession(
  libraryId: string,
  password: string,
  legacyPasskey?: string,
): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_unlock', {
    libraryId,
    password,
    ...(legacyPasskey ? { legacyPasskey } : {}),
  })
}

export async function lockColdPassSession(libraryId: string): Promise<void> {
  await invokeColdPass('coldpass_lock', { libraryId })
}

/** Adds a credential, or edits `entryId` keeping its password history. */
export async function saveColdPassEntry(
  libraryId: string,
  entry: ColdPassEntry,
  entryId?: string,
): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_save_entry', {
    libraryId,
    entry,
    ...(entryId ? { entryId } : {}),
  })
}

export async function deleteColdPassEntry(
  libraryId: string,
  entryId: string,
  password: string,
): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_delete_entry', { libraryId, entryId, password })
}

/** Opens the native picker in the backend; `null` when cancelled. */
export async function pickColdPassCsvImport(libraryId: string): Promise<ColdPassImportPreview | null> {
  return invokeColdPass<ColdPassImportPreview | null>('coldpass_pick_csv_import', { libraryId })
}

export async function confirmColdPassImport(libraryId: string, password: string): Promise<ColdPassSessionData> {
  return invokeColdPass<ColdPassSessionData>('coldpass_confirm_import', { libraryId, password })
}

export async function getColdPassStatus(libraryId: string): Promise<ColdPassStatus> {
  return invokeColdPass<ColdPassStatus>('coldpass_status', { libraryId })
}

/** A random password generated by the backend and its brute-force estimate. */
export async function generateColdPassPassword(
  options: ColdPassPasswordOptions,
): Promise<{ password: string; bruteForceSeconds: number }> {
  return invokeColdPass<{ password: string; bruteForceSeconds: number }>('coldpass_generate_password', { options })
}

/**
 * Copies a secret to the clipboard of this device. The backend clears it
 * after `clearsAfterSeconds` if nothing else was copied; `null` means this
 * device cannot, and the text was copied without the automatic clearing.
 */
export async function copyColdPassSecret(text: string): Promise<{ clearsAfterSeconds: number } | null> {
  try {
    return await callBackend<{ clearsAfterSeconds: number }>('coldpass_copy_secret', { payload: { text } })
  } catch {
    await navigator.clipboard.writeText(text)
    return null
  }
}
